## Docker ESPHome using Docker Compose

/data/docker/esphome/docker-compose.yml

run ok 20250125

~~~
services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - /data/docker/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=esphome
      - PASSWORD=esphome

~~~



~~~
services:
  esphome:
    #image: esphome/esphome:beta
    #image: esphome/esphome:dev
    # image: esphome/esphome:latest
    image: ghcr.io/esphome/esphome:stable
    # image: esphome/esphome:2023.5.5
    devices:
      #  - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/bus/usb:/dev/bus/usb"
    # - "/dev/ttyS3:/dev/ttyUSB0"
    privileged: true
    container_name: esphome
    volumes:
      - ./config:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    # network_mode: host
    environment:
      - com.centurylinklabs.watchtower.enable=1
      - ESPHOME_DASHBOARD_USE_PING=true
      - USERNAME=test
      - PASSWORD=test

    ports:
      - 6152:6052
      - 6123:6123
    restart: unless-stopped

~~~ 